global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: careerai

scrape_configs:
  - job_name: api-gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8080"]
        labels:
          application: api-gateway

  - job_name: auth-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8081"]
        labels:
          application: auth-service

  - job_name: resume-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8082"]
        labels:
          application: resume-service

  - job_name: interview-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8083"]
        labels:
          application: interview-service

  - job_name: job-match-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8084"]
        labels:
          application: job-match-service
