package com.careerai.jobmatch.mapper;

import com.careerai.jobmatch.domain.entity.JobListing;
import com.careerai.jobmatch.domain.entity.JobMatch;
import com.careerai.jobmatch.dto.ai.SkillGapResult;
import com.careerai.jobmatch.dto.response.JobListingResponse;
import com.careerai.jobmatch.dto.response.JobMatchResponse;
import com.careerai.jobmatch.dto.response.LearningPathResponse;
import com.careerai.jobmatch.dto.response.SkillGapResponse;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.springframework.beans.factory.annotation.Autowired;

import java.util.List;

/**
 * Maps job-match entities to their public DTOs. Straightforward field copies are generated by
 * MapStruct; JSON-array TEXT columns are expanded into lists via {@link #toStringList(String)}. The
 * skill-gap / learning-path views are assembled by hand from the Claude result record.
 */
@Mapper(componentModel = "spring")
public abstract class JobMatchMapper {

    private static final TypeReference<List<String>> STRING_LIST = new TypeReference<>() {
    };

    @Autowired
    protected ObjectMapper objectMapper;

    public abstract JobListingResponse toJobListingResponse(JobListing listing);

    @Mapping(target = "matchId", source = "id")
    @Mapping(target = "job", source = "jobListing")
    public abstract JobMatchResponse toJobMatchResponse(JobMatch match);

    /**
     * Builds the skill-gap view, attaching the job title (which Claude is not asked to echo back).
     */
    public SkillGapResponse toSkillGapResponse(String jobTitle, SkillGapResult result) {
        List<SkillGapResponse.PartialMatch> partials = result.partialMatches() == null
                ? List.of()
                : result.partialMatches().stream()
                .map(p -> new SkillGapResponse.PartialMatch(p.skill(), p.candidateLevel(), p.requiredLevel()))
                .toList();
        return new SkillGapResponse(
                jobTitle,
                nullToEmpty(result.matchedSkills()),
                nullToEmpty(result.missingSkills()),
                partials,
                result.gapScore(),
                result.readinessLevel(),
                result.summary());
    }

    /**
     * Builds the learning-path view from the same Claude result, summing per-skill effort estimates.
     */
    public LearningPathResponse toLearningPathResponse(String jobTitle, SkillGapResult result) {
        List<SkillGapResult.LearningPathItem> items = result.learningPath() == null
                ? List.of()
                : result.learningPath();

        List<LearningPathResponse.PrioritisedSkill> skills = items.stream()
                .map(item -> new LearningPathResponse.PrioritisedSkill(
                        item.skill(),
                        item.priority(),
                        item.estimatedWeeks(),
                        item.resources() == null ? List.of() : item.resources().stream()
                                .map(r -> new LearningPathResponse.Resource(r.title(), r.url(), r.type()))
                                .toList()))
                .toList();

        int totalWeeks = items.stream()
                .map(SkillGapResult.LearningPathItem::estimatedWeeks)
                .filter(w -> w != null)
                .mapToInt(Integer::intValue)
                .sum();

        return new LearningPathResponse(jobTitle, totalWeeks, skills);
    }

    /**
     * Parses a JSON-array string into a list, returning an empty list for null/blank/invalid input.
     */
    protected List<String> toStringList(String json) {
        if (json == null || json.isBlank()) {
            return List.of();
        }
        try {
            List<String> values = objectMapper.readValue(json, STRING_LIST);
            return values != null ? values : List.of();
        } catch (JsonProcessingException e) {
            return List.of();
        }
    }

    private List<String> nullToEmpty(List<String> values) {
        return values == null ? List.of() : values;
    }
}
