package com.careerai.resume.mapper;

import com.careerai.resume.domain.entity.Resume;
import com.careerai.resume.domain.entity.ResumeAnalysis;
import com.careerai.resume.domain.entity.SkillExtraction;
import com.careerai.resume.dto.response.ResumeAnalysisResponse;
import com.careerai.resume.dto.response.ResumeResponse;
import com.careerai.resume.dto.response.SkillExtractionResponse;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.mapstruct.Mapper;
import org.springframework.beans.factory.annotation.Autowired;

import java.util.List;

/**
 * Maps resume entities to their public DTOs. The straightforward field copies are generated by
 * MapStruct; the JSON-array TEXT columns on {@link ResumeAnalysis} are expanded back into lists
 * here using the shared {@link ObjectMapper}.
 */
@Mapper(componentModel = "spring")
public abstract class ResumeMapper {

    private static final TypeReference<List<String>> STRING_LIST = new TypeReference<>() {
    };

    @Autowired
    protected ObjectMapper objectMapper;

    public abstract ResumeResponse toResumeResponse(Resume resume);

    public abstract SkillExtractionResponse toSkillResponse(SkillExtraction skill);

    public ResumeAnalysisResponse toAnalysisResponse(ResumeAnalysis analysis) {
        if (analysis == null) {
            return null;
        }
        List<SkillExtractionResponse> skills = analysis.getSkills() == null
                ? List.of()
                : analysis.getSkills().stream().map(this::toSkillResponse).toList();
        return new ResumeAnalysisResponse(
                analysis.getId(),
                analysis.getResume() != null ? analysis.getResume().getId() : null,
                analysis.getAtsScore(),
                analysis.getSummary(),
                analysis.getYearsOfExperience(),
                analysis.getEducationLevel(),
                toStringList(analysis.getTargetRoles()),
                toStringList(analysis.getStrengths()),
                toStringList(analysis.getWeaknesses()),
                toStringList(analysis.getSuggestions()),
                toStringList(analysis.getKeywords()),
                toStringList(analysis.getMissingKeywords()),
                skills,
                analysis.getCreatedAt());
    }

    /**
     * Parses a JSON-array string into a list, returning an empty list for null/blank/invalid input.
     */
    protected List<String> toStringList(String json) {
        if (json == null || json.isBlank()) {
            return List.of();
        }
        try {
            List<String> values = objectMapper.readValue(json, STRING_LIST);
            return values != null ? values : List.of();
        } catch (JsonProcessingException e) {
            return List.of();
        }
    }
}
