package com.careerai.interview.mapper;

import com.careerai.interview.domain.entity.InterviewFeedback;
import com.careerai.interview.domain.entity.InterviewQuestion;
import com.careerai.interview.domain.entity.InterviewSession;
import com.careerai.interview.dto.response.FeedbackResponse;
import com.careerai.interview.dto.response.QuestionResponse;
import com.careerai.interview.dto.response.SessionResponse;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.mapstruct.Mapper;
import org.springframework.beans.factory.annotation.Autowired;

import java.util.List;

/**
 * Maps interview entities to their public DTOs. Straightforward field copies are generated by
 * MapStruct; the JSON-array TEXT columns on {@link InterviewFeedback} are expanded back into lists
 * here using the shared {@link ObjectMapper}.
 */
@Mapper(componentModel = "spring")
public abstract class InterviewMapper {

    private static final TypeReference<List<String>> STRING_LIST = new TypeReference<>() {
    };
    private static final TypeReference<List<FeedbackResponse.RecommendedResource>> RESOURCE_LIST =
            new TypeReference<>() {
            };

    @Autowired
    protected ObjectMapper objectMapper;

    public abstract SessionResponse toSessionResponse(InterviewSession session);

    public QuestionResponse toQuestionResponse(InterviewQuestion question) {
        if (question == null) {
            return null;
        }
        Integer total = question.getSession() != null ? question.getSession().getTotalQuestions() : null;
        return new QuestionResponse(
                question.getId(),
                question.getQuestionNumber(),
                question.getQuestionText(),
                question.getType(),
                question.getDifficulty(),
                total);
    }

    public FeedbackResponse toFeedbackResponse(InterviewFeedback feedback) {
        if (feedback == null) {
            return null;
        }
        InterviewSession session = feedback.getSession();
        return new FeedbackResponse(
                feedback.getId(),
                session != null ? session.getId() : null,
                session != null ? session.getOverallScore() : null,
                feedback.getTechnicalScore(),
                feedback.getBehaviouralScore(),
                feedback.getCommunicationScore(),
                feedback.getProblemSolvingScore(),
                toStringList(feedback.getStrongAreas()),
                toStringList(feedback.getImprovementAreas()),
                feedback.getDetailedFeedback(),
                toResourceList(feedback.getRecommendedResources()),
                feedback.getGeneratedAt());
    }

    /** Parses a JSON-array string into a list, returning an empty list for null/blank/invalid input. */
    protected List<String> toStringList(String json) {
        if (json == null || json.isBlank()) {
            return List.of();
        }
        try {
            List<String> values = objectMapper.readValue(json, STRING_LIST);
            return values != null ? values : List.of();
        } catch (JsonProcessingException e) {
            return List.of();
        }
    }

    protected List<FeedbackResponse.RecommendedResource> toResourceList(String json) {
        if (json == null || json.isBlank()) {
            return List.of();
        }
        try {
            List<FeedbackResponse.RecommendedResource> values = objectMapper.readValue(json, RESOURCE_LIST);
            return values != null ? values : List.of();
        } catch (JsonProcessingException e) {
            return List.of();
        }
    }
}
